### ISSUE TITLE
All rejections are bundled together with same title 

### ISSUE THREAD

**Issue by davidpp** [bahmutov/report-rejected-promises-to-sentry#1]
All errors are reported as coming from /app/node_modules/report-rejected-promises-to-sentry/src/index.js in process.on at line 20:17 so all Promises rejections are bundled together.

**Comment by bahmutov** [comment]
hmm, do the promises actually have a valid stack? If you register your own promise rejection handler, does it have a valid stack?

**Comment by davidpp** [comment]
hey sorry my bad, just realized that sentry (Node.js) support promise reporting without a third party package.  Yours is probably intended for the browser?
